name: builds

on:
  push:
  pull_request:

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@master

    - name: Install NuGet packages
      run: nuget restore

    - name: Build the tool
      run: msbuild HATE.sln /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    #- name: Run unit tests
    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        name: HATE-${{ matrix.configuration }}
        path: |
          HATE\bin\${{ matrix.configuration }}
